// GENERATED by tools/gen-li-art.mjs --wire. Do not edit by hand.
// Two generated maps that wire the cast portraits into the game:
//   PORTRAITS         slot ("<castId>" | "<castId>_<mood>") → the fallback <img> src
//   PORTRAIT_VARIANTS that src → its responsive AVIF/WebP/JPEG srcset ladder
// Both served from docs/games/love-island/public/ → dist/love-island/. Empty
// until portraits are generated (every face then falls back to its emoji glyph,
// identical to pre-art behaviour), so this file is golden-safe. The variant sets
// are produced by the generic preprocessing engine (tools/image-core.mjs) so a
// small face chip fetches a ~2KB AVIF, not a 750KB master — see the SOTA-image ADR.
import type { ImageVariant } from '../../types.js';

export const PORTRAITS: Record<string, string> = {
  "amber": "art/cast/amber-384.jpg",
  "bella": "art/cast/bella-384.jpg",
  "chloe": "art/cast/chloe-384.jpg",
  "dev": "art/cast/dev-384.jpg",
  "jamal": "art/cast/jamal-384.jpg",
  "kai": "art/cast/kai-384.jpg",
  "luca": "art/cast/luca-384.jpg",
  "marco": "art/cast/marco-384.jpg",
  "meg": "art/cast/meg-384.jpg",
  "ollie": "art/cast/ollie-384.jpg",
  "priya": "art/cast/priya-384.jpg",
  "reece": "art/cast/reece-384.jpg",
  "sophia": "art/cast/sophia-384.jpg",
  "tash": "art/cast/tash-384.jpg",
  "tyler": "art/cast/tyler-384.jpg",
  "zara": "art/cast/zara-384.jpg"
};

export const PORTRAIT_VARIANTS: Record<string, ImageVariant> = {
  "art/cast/amber-384.jpg": {
    "w": 384,
    "h": 384,
    "avif": "art/cast/amber-96.avif 96w, art/cast/amber-192.avif 192w, art/cast/amber-384.avif 384w, art/cast/amber-768.avif 768w",
    "webp": "art/cast/amber-96.webp 96w, art/cast/amber-192.webp 192w, art/cast/amber-384.webp 384w, art/cast/amber-768.webp 768w",
    "jpeg": "art/cast/amber-96.jpg 96w, art/cast/amber-192.jpg 192w, art/cast/amber-384.jpg 384w, art/cast/amber-768.jpg 768w"
  },
  "art/cast/bella-384.jpg": {
    "w": 384,
    "h": 384,
    "avif": "art/cast/bella-96.avif 96w, art/cast/bella-192.avif 192w, art/cast/bella-384.avif 384w, art/cast/bella-768.avif 768w",
    "webp": "art/cast/bella-96.webp 96w, art/cast/bella-192.webp 192w, art/cast/bella-384.webp 384w, art/cast/bella-768.webp 768w",
    "jpeg": "art/cast/bella-96.jpg 96w, art/cast/bella-192.jpg 192w, art/cast/bella-384.jpg 384w, art/cast/bella-768.jpg 768w"
  },
  "art/cast/chloe-384.jpg": {
    "w": 384,
    "h": 384,
    "avif": "art/cast/chloe-96.avif 96w, art/cast/chloe-192.avif 192w, art/cast/chloe-384.avif 384w, art/cast/chloe-768.avif 768w",
    "webp": "art/cast/chloe-96.webp 96w, art/cast/chloe-192.webp 192w, art/cast/chloe-384.webp 384w, art/cast/chloe-768.webp 768w",
    "jpeg": "art/cast/chloe-96.jpg 96w, art/cast/chloe-192.jpg 192w, art/cast/chloe-384.jpg 384w, art/cast/chloe-768.jpg 768w"
  },
  "art/cast/dev-384.jpg": {
    "w": 384,
    "h": 384,
    "avif": "art/cast/dev-96.avif 96w, art/cast/dev-192.avif 192w, art/cast/dev-384.avif 384w, art/cast/dev-768.avif 768w",
    "webp": "art/cast/dev-96.webp 96w, art/cast/dev-192.webp 192w, art/cast/dev-384.webp 384w, art/cast/dev-768.webp 768w",
    "jpeg": "art/cast/dev-96.jpg 96w, art/cast/dev-192.jpg 192w, art/cast/dev-384.jpg 384w, art/cast/dev-768.jpg 768w"
  },
  "art/cast/jamal-384.jpg": {
    "w": 384,
    "h": 384,
    "avif": "art/cast/jamal-96.avif 96w, art/cast/jamal-192.avif 192w, art/cast/jamal-384.avif 384w, art/cast/jamal-768.avif 768w",
    "webp": "art/cast/jamal-96.webp 96w, art/cast/jamal-192.webp 192w, art/cast/jamal-384.webp 384w, art/cast/jamal-768.webp 768w",
    "jpeg": "art/cast/jamal-96.jpg 96w, art/cast/jamal-192.jpg 192w, art/cast/jamal-384.jpg 384w, art/cast/jamal-768.jpg 768w"
  },
  "art/cast/kai-384.jpg": {
    "w": 384,
    "h": 384,
    "avif": "art/cast/kai-96.avif 96w, art/cast/kai-192.avif 192w, art/cast/kai-384.avif 384w, art/cast/kai-768.avif 768w",
    "webp": "art/cast/kai-96.webp 96w, art/cast/kai-192.webp 192w, art/cast/kai-384.webp 384w, art/cast/kai-768.webp 768w",
    "jpeg": "art/cast/kai-96.jpg 96w, art/cast/kai-192.jpg 192w, art/cast/kai-384.jpg 384w, art/cast/kai-768.jpg 768w"
  },
  "art/cast/luca-384.jpg": {
    "w": 384,
    "h": 384,
    "avif": "art/cast/luca-96.avif 96w, art/cast/luca-192.avif 192w, art/cast/luca-384.avif 384w, art/cast/luca-768.avif 768w",
    "webp": "art/cast/luca-96.webp 96w, art/cast/luca-192.webp 192w, art/cast/luca-384.webp 384w, art/cast/luca-768.webp 768w",
    "jpeg": "art/cast/luca-96.jpg 96w, art/cast/luca-192.jpg 192w, art/cast/luca-384.jpg 384w, art/cast/luca-768.jpg 768w"
  },
  "art/cast/marco-384.jpg": {
    "w": 384,
    "h": 384,
    "avif": "art/cast/marco-96.avif 96w, art/cast/marco-192.avif 192w, art/cast/marco-384.avif 384w, art/cast/marco-768.avif 768w",
    "webp": "art/cast/marco-96.webp 96w, art/cast/marco-192.webp 192w, art/cast/marco-384.webp 384w, art/cast/marco-768.webp 768w",
    "jpeg": "art/cast/marco-96.jpg 96w, art/cast/marco-192.jpg 192w, art/cast/marco-384.jpg 384w, art/cast/marco-768.jpg 768w"
  },
  "art/cast/meg-384.jpg": {
    "w": 384,
    "h": 384,
    "avif": "art/cast/meg-96.avif 96w, art/cast/meg-192.avif 192w, art/cast/meg-384.avif 384w, art/cast/meg-768.avif 768w",
    "webp": "art/cast/meg-96.webp 96w, art/cast/meg-192.webp 192w, art/cast/meg-384.webp 384w, art/cast/meg-768.webp 768w",
    "jpeg": "art/cast/meg-96.jpg 96w, art/cast/meg-192.jpg 192w, art/cast/meg-384.jpg 384w, art/cast/meg-768.jpg 768w"
  },
  "art/cast/ollie-384.jpg": {
    "w": 384,
    "h": 384,
    "avif": "art/cast/ollie-96.avif 96w, art/cast/ollie-192.avif 192w, art/cast/ollie-384.avif 384w, art/cast/ollie-768.avif 768w",
    "webp": "art/cast/ollie-96.webp 96w, art/cast/ollie-192.webp 192w, art/cast/ollie-384.webp 384w, art/cast/ollie-768.webp 768w",
    "jpeg": "art/cast/ollie-96.jpg 96w, art/cast/ollie-192.jpg 192w, art/cast/ollie-384.jpg 384w, art/cast/ollie-768.jpg 768w"
  },
  "art/cast/priya-384.jpg": {
    "w": 384,
    "h": 384,
    "avif": "art/cast/priya-96.avif 96w, art/cast/priya-192.avif 192w, art/cast/priya-384.avif 384w, art/cast/priya-768.avif 768w",
    "webp": "art/cast/priya-96.webp 96w, art/cast/priya-192.webp 192w, art/cast/priya-384.webp 384w, art/cast/priya-768.webp 768w",
    "jpeg": "art/cast/priya-96.jpg 96w, art/cast/priya-192.jpg 192w, art/cast/priya-384.jpg 384w, art/cast/priya-768.jpg 768w"
  },
  "art/cast/reece-384.jpg": {
    "w": 384,
    "h": 384,
    "avif": "art/cast/reece-96.avif 96w, art/cast/reece-192.avif 192w, art/cast/reece-384.avif 384w, art/cast/reece-768.avif 768w",
    "webp": "art/cast/reece-96.webp 96w, art/cast/reece-192.webp 192w, art/cast/reece-384.webp 384w, art/cast/reece-768.webp 768w",
    "jpeg": "art/cast/reece-96.jpg 96w, art/cast/reece-192.jpg 192w, art/cast/reece-384.jpg 384w, art/cast/reece-768.jpg 768w"
  },
  "art/cast/sophia-384.jpg": {
    "w": 384,
    "h": 384,
    "avif": "art/cast/sophia-96.avif 96w, art/cast/sophia-192.avif 192w, art/cast/sophia-384.avif 384w, art/cast/sophia-768.avif 768w",
    "webp": "art/cast/sophia-96.webp 96w, art/cast/sophia-192.webp 192w, art/cast/sophia-384.webp 384w, art/cast/sophia-768.webp 768w",
    "jpeg": "art/cast/sophia-96.jpg 96w, art/cast/sophia-192.jpg 192w, art/cast/sophia-384.jpg 384w, art/cast/sophia-768.jpg 768w"
  },
  "art/cast/tash-384.jpg": {
    "w": 384,
    "h": 384,
    "avif": "art/cast/tash-96.avif 96w, art/cast/tash-192.avif 192w, art/cast/tash-384.avif 384w, art/cast/tash-768.avif 768w",
    "webp": "art/cast/tash-96.webp 96w, art/cast/tash-192.webp 192w, art/cast/tash-384.webp 384w, art/cast/tash-768.webp 768w",
    "jpeg": "art/cast/tash-96.jpg 96w, art/cast/tash-192.jpg 192w, art/cast/tash-384.jpg 384w, art/cast/tash-768.jpg 768w"
  },
  "art/cast/tyler-384.jpg": {
    "w": 384,
    "h": 384,
    "avif": "art/cast/tyler-96.avif 96w, art/cast/tyler-192.avif 192w, art/cast/tyler-384.avif 384w, art/cast/tyler-768.avif 768w",
    "webp": "art/cast/tyler-96.webp 96w, art/cast/tyler-192.webp 192w, art/cast/tyler-384.webp 384w, art/cast/tyler-768.webp 768w",
    "jpeg": "art/cast/tyler-96.jpg 96w, art/cast/tyler-192.jpg 192w, art/cast/tyler-384.jpg 384w, art/cast/tyler-768.jpg 768w"
  },
  "art/cast/zara-384.jpg": {
    "w": 384,
    "h": 384,
    "avif": "art/cast/zara-96.avif 96w, art/cast/zara-192.avif 192w, art/cast/zara-384.avif 384w, art/cast/zara-768.avif 768w",
    "webp": "art/cast/zara-96.webp 96w, art/cast/zara-192.webp 192w, art/cast/zara-384.webp 384w, art/cast/zara-768.webp 768w",
    "jpeg": "art/cast/zara-96.jpg 96w, art/cast/zara-192.jpg 192w, art/cast/zara-384.jpg 384w, art/cast/zara-768.jpg 768w"
  }
};
