// Contestant portrait resolution — the runtime seam mirroring js/art.ts's
// "real asset wins, else fall back" rule, but for the cast's mood-driven faces
// (which render through characterRead, not artFor). Returns a web path when a
// generated portrait exists for this contestant+mood, else undefined so the
// caller keeps the emoji glyph. The map is generated by tools/gen-li-art.mjs
// and is empty by default, so with no art present behaviour is unchanged.
import { PORTRAITS } from './portraits.data.js';

// Most specific first: a mood-specific portrait, then the contestant's hero
// portrait (worn under any mood via the emoji mood badge), then nothing.
export function portraitSrc(castId?: string | null, mood?: string | null): string | undefined {
  if (!castId) return undefined;
  return (mood && PORTRAITS[`${castId}_${mood}`]) || PORTRAITS[castId] || undefined;
}
