// GENERATED by tools/gen-li-art.mjs --wire. Do not edit by hand.
// Maps a portrait slot ("<castId>" or "<castId>_<mood>") to its deploy path,
// served from docs/games/love-island/public/ → dist/love-island/. Empty until
// portraits are generated; an empty map means every face falls back to its
// emoji glyph (identical to pre-art behaviour), so this file is golden-safe.
export const PORTRAITS: Record<string, string> = {};
